name: Delpoy Application

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Deploy version"
        required: true
        default: "v1.0.0"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create deployment package
        run: |
          zip -r deployment.zip . -x "*.git*" ".github/*"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment.zip

  deploy-to-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
          token: ${{ secrets.WIKI_TOKEN }}
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
      
      - name: Verify deployment package
        run: |
          echo "Verifying deployment package exists..."
          if [ -f "deployment.zip" ]; then
            echo "deployment.zip found successfully"
          else
            echo "deployment.zip not found"
            exit 1
          fi
          echo "Deploying version ${{ github.event.inputs.version }} to staging"
          # Add your deployment script here
      
      - name: Update deployment log
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_TOKEN }}
        run: |
          cd wiki
          echo "| $(date -u '+%Y-%m-%d %H:%M:%S UTC') | Staging | ${{ github.run_number }} | ${{ github.actor }} |" >> Deployment-Log.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.wiki.git
          git add Deployment-Log.md
          git commit -m "Log staging deployment #${{ github.run_number }}"
          git push

  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-to-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
          token: ${{ secrets.WIKI_TOKEN }}
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
      
      - name: Verify deployment package
        run: |
          echo "Verifying deployment package exists..."
          if [ -f "deployment.zip" ]; then
            echo "deployment.zip found successfully"
          else
            echo "deployment.zip not found"
            exit 1
          fi
          echo "Deploying version ${{ github.event.inputs.version }} to production"
          # Add your deployment script here
      
      - name: Update deployment log
        env:
          GITHUB_TOKEN: ${{ secrets.WIKI_TOKEN }}
        run: |
          cd wiki
          echo "| $(date -u '+%Y-%m-%d %H:%M:%S UTC') | Production | ${{ github.run_number }} | ${{ github.actor }} |" >> Deployment-Log.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.wiki.git
          git add Deployment-Log.md
          git commit -m "Log production deployment #${{ github.run_number }}"
          git push



