name: Deploy Application

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Deploy version"
        required: true
        default: "v1.0.0"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create deployment package
        run: |
          zip -r deployment.zip . -x "*.git*" ".github/*"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment.zip

  deploy-to-staging:
    needs: build
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
      
      - name: Verify deployment package
        run: |
          echo "Verifying deployment package exists..."
          if [ -f "deployment.zip" ]; then
            echo "deployment.zip found successfully"
          else
            echo "deployment.zip not found"
            exit 1
          fi
          echo "Deploying version ${{ github.event.inputs.version }} to staging"
          # Add your deployment script here

      - name: Log staging deployment
        uses: ./.github/actions/update-wiki
        with:
          environment: 'Staging'
          run_number: ${{ github.run_number }}
          actor: ${{ github.actor }}
          version: ${{ github.event.inputs.version }}
          token: ${{ secrets.WIKI_TOKEN }}

  deploy-to-production:
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-to-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-package
      
      - name: Verify deployment package
        run: |
          echo "Verifying deployment package exists..."
          if [ -f "deployment.zip" ]; then
            echo "deployment.zip found successfully"
          else
            echo "deployment.zip not found"
            exit 1
          fi
          echo "Deploying version ${{ github.event.inputs.version }} to production"
          # Add your deployment script here

      - name: Log production deployment
        uses: ./.github/actions/update-wiki
        with:
          environment: 'Production'
          run_number: ${{ github.run_number }}
          actor: ${{ github.actor }}
          version: ${{ github.event.inputs.version }}
          token: ${{ secrets.WIKI_TOKEN }}



